/**
 * 預設模板定義
 * 提供多種專業設計的展覽網站模板
 */

export interface PresetTemplate {
  id: string
  name: string
  description: string
  thumbnail: string
  category: 'minimalist' | 'modern' | 'artistic' | 'gallery' | 'corporate'
  templateJson: Record<string, any>
}

export const presetTemplates: PresetTemplate[] = [
  {
    id: 'blank',
    name: '空白模板',
    description: '從零開始，完全自由設計',
    thumbnail: '/templates/blank.png',
    category: 'minimalist',
    templateJson: {
      ROOT: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 40, background: '#ffffff' },
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
    },
  },
  {
    id: 'minimalist',
    name: '極簡風格',
    description: '簡潔俐落的設計，突出作品本身',
    thumbnail: '/templates/minimalist.png',
    category: 'minimalist',
    templateJson: {
      ROOT: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 0, background: '#ffffff' },
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['hero', 'intro', 'cta'],
        linkedNodes: {},
      },
      hero: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {
          padding: 80,
          background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        },
        displayName: 'Hero Section',
        parent: 'ROOT',
        custom: {},
        hidden: false,
        nodes: ['hero-title', 'hero-subtitle'],
        linkedNodes: {},
      },
      'hero-title': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '2024 畢業展覽',
          fontSize: 48,
          fontWeight: 700,
          color: '#ffffff',
          textAlign: 'center',
        },
        displayName: 'Title',
        parent: 'hero',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      'hero-subtitle': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '青春的印記，創意的綻放',
          fontSize: 24,
          fontWeight: 400,
          color: '#f0f0f0',
          textAlign: 'center',
        },
        displayName: 'Subtitle',
        parent: 'hero',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      intro: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 60, background: '#f8f9fa' },
        displayName: 'Intro Section',
        parent: 'ROOT',
        custom: {},
        hidden: false,
        nodes: ['intro-title', 'intro-text'],
        linkedNodes: {},
      },
      'intro-title': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '關於本展',
          fontSize: 36,
          fontWeight: 700,
          color: '#1a1a1a',
          textAlign: 'center',
        },
        displayName: 'Section Title',
        parent: 'intro',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      'intro-text': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '歡迎來到我們的展覽。這裡展示了學生們的創意作品，每一件都是心血結晶。',
          fontSize: 18,
          fontWeight: 400,
          color: '#666666',
          textAlign: 'center',
        },
        displayName: 'Description',
        parent: 'intro',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      cta: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 60, background: '#ffffff' },
        displayName: 'CTA Section',
        parent: 'ROOT',
        custom: {},
        hidden: false,
        nodes: ['cta-button'],
        linkedNodes: {},
      },
      'cta-button': {
        type: { resolvedName: 'Button' },
        isCanvas: false,
        props: {
          text: '探索作品',
          backgroundColor: '#667eea',
          color: '#ffffff',
          fontSize: 18,
          padding: 15,
          borderRadius: 8,
          href: '#artworks',
        },
        displayName: 'CTA Button',
        parent: 'cta',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
    },
  },
  {
    id: 'modern',
    name: '現代風格',
    description: '大膽的色彩與排版，充滿活力',
    thumbnail: '/templates/modern.png',
    category: 'modern',
    templateJson: {
      ROOT: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 0, background: '#0f0f0f' },
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['header', 'feature', 'footer'],
        linkedNodes: {},
      },
      header: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {
          padding: 100,
          background: 'linear-gradient(90deg, #ff6b6b 0%, #feca57 100%)',
        },
        displayName: 'Header',
        parent: 'ROOT',
        custom: {},
        hidden: false,
        nodes: ['header-title', 'header-desc'],
        linkedNodes: {},
      },
      'header-title': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '創新 · 突破 · 未來',
          fontSize: 56,
          fontWeight: 800,
          color: '#ffffff',
          textAlign: 'left',
        },
        displayName: 'Header Title',
        parent: 'header',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      'header-desc': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '探索新世代設計師的無限可能',
          fontSize: 20,
          fontWeight: 500,
          color: '#ffffff',
          textAlign: 'left',
        },
        displayName: 'Header Description',
        parent: 'header',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      feature: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 80, background: '#1a1a1a' },
        displayName: 'Feature Section',
        parent: 'ROOT',
        custom: {},
        hidden: false,
        nodes: ['feature-title', 'feature-text'],
        linkedNodes: {},
      },
      'feature-title': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '作品特色',
          fontSize: 42,
          fontWeight: 700,
          color: '#feca57',
          textAlign: 'center',
        },
        displayName: 'Feature Title',
        parent: 'feature',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      'feature-text': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '每件作品都代表著創作者的獨特視角與創意思維',
          fontSize: 18,
          fontWeight: 400,
          color: '#cccccc',
          textAlign: 'center',
        },
        displayName: 'Feature Text',
        parent: 'feature',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      footer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 40, background: '#0f0f0f' },
        displayName: 'Footer',
        parent: 'ROOT',
        custom: {},
        hidden: false,
        nodes: ['footer-text'],
        linkedNodes: {},
      },
      'footer-text': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: '© 2024 畢業展覽 版權所有',
          fontSize: 14,
          fontWeight: 400,
          color: '#666666',
          textAlign: 'center',
        },
        displayName: 'Copyright',
        parent: 'footer',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
    },
  },
  {
    id: 'gallery',
    name: '藝廊風格',
    description: '專業藝廊氛圍，聚焦視覺體驗',
    thumbnail: '/templates/gallery.png',
    category: 'gallery',
    templateJson: {
      ROOT: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 0, background: '#fafafa' },
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['banner', 'gallery-intro'],
        linkedNodes: {},
      },
      banner: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 120, background: '#2c3e50' },
        displayName: 'Banner',
        parent: 'ROOT',
        custom: {},
        hidden: false,
        nodes: ['banner-title', 'banner-subtitle'],
        linkedNodes: {},
      },
      'banner-title': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: 'ART EXHIBITION 2024',
          fontSize: 52,
          fontWeight: 300,
          color: '#ecf0f1',
          textAlign: 'center',
          letterSpacing: '0.2em',
        },
        displayName: 'Banner Title',
        parent: 'banner',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      'banner-subtitle': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: 'A VISUAL JOURNEY',
          fontSize: 16,
          fontWeight: 400,
          color: '#bdc3c7',
          textAlign: 'center',
          letterSpacing: '0.3em',
        },
        displayName: 'Banner Subtitle',
        parent: 'banner',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      'gallery-intro': {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { padding: 80, background: '#ffffff' },
        displayName: 'Gallery Intro',
        parent: 'ROOT',
        custom: {},
        hidden: false,
        nodes: ['gallery-title', 'gallery-desc'],
        linkedNodes: {},
      },
      'gallery-title': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: 'CURATED COLLECTION',
          fontSize: 38,
          fontWeight: 300,
          color: '#2c3e50',
          textAlign: 'center',
          letterSpacing: '0.1em',
        },
        displayName: 'Gallery Title',
        parent: 'gallery-intro',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      'gallery-desc': {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: {
          text: 'Discover the finest works from emerging artists',
          fontSize: 18,
          fontWeight: 400,
          color: '#7f8c8d',
          textAlign: 'center',
        },
        displayName: 'Gallery Description',
        parent: 'gallery-intro',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
    },
  },
]

/**
 * 根據 ID 獲取預設模板
 */
export function getPresetTemplateById(id: string): PresetTemplate | undefined {
  return presetTemplates.find((t) => t.id === id)
}

/**
 * 根據分類獲取預設模板
 */
export function getPresetTemplatesByCategory(
  category: PresetTemplate['category']
): PresetTemplate[] {
  return presetTemplates.filter((t) => t.category === category)
}
